"""initial_player_registry

Revision ID: 04bbb7370b42
Revises: 
Create Date: 2026-04-13 19:34:12.680697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04bbb7370b42'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('game_id', sa.String(length=4), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('ended_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('winner_team', sa.String(length=16), nullable=True),
    sa.Column('player_count', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_table('players',
    sa.Column('permanent_id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('permanent_id')
    )
    op.create_table('game_players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.String(length=4), nullable=False),
    sa.Column('permanent_id', sa.String(length=36), nullable=False),
    sa.Column('per_game_player_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ),
    sa.ForeignKeyConstraint(['permanent_id'], ['players.permanent_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'permanent_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_players')
    op.drop_table('players')
    op.drop_table('games')
    # ### end Alembic commands ###
